runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: FwQ0TUm/dMH8SGTbkFoX7lG+SB4pumdLQPPn56XYxb4=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie